const collegeSeatsWithId = {
  1: {
    general_seats: 0,
    obc_seats: 26,
    sc_seats: 14,
    st_seats: 5,
    ews_seats: 9,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  2: {
    general_seats: 0,
    obc_seats: 12,
    sc_seats: 6,
    st_seats: 3,
    ews_seats: 5,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  3: {
    general_seats: 0,
    obc_seats: 12,
    sc_seats: 9,
    st_seats: 3,
    ews_seats: 5,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  4: {
    general_seats: 0,
    obc_seats: 26,
    sc_seats: 13,
    st_seats: 6,
    ews_seats: 8,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  5: {
    general_seats: 0,
    obc_seats: 30,
    sc_seats: 13,
    st_seats: 6,
    ews_seats: 9,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  6: {
    general_seats: 0,
    obc_seats: 13,
    sc_seats: 8,
    st_seats: 2,
    ews_seats: 2,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  7: {
    general_seats: 0,
    obc_seats: 6,
    sc_seats: 5,
    st_seats: 0,
    ews_seats: 0,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  8: {
    general_seats: 0,
    obc_seats: 28,
    sc_seats: 11,
    st_seats: 5,
    ews_seats: 7,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  9: {
    general_seats: 0,
    obc_seats: 25,
    sc_seats: 12,
    st_seats: 6,
    ews_seats: 9,
    pwd_general_seats: 0,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  10: {
    general_seats: 12,
    obc_seats: 8,
    sc_seats: 4,
    st_seats: 3,
    ews_seats: 2,
    pwd_general_seats: 1,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
};

module.exports = collegeSeatsWithId;
