const collegeSeatsWithId = {
  1: {
    general_seats: 45,
    obc_seats: 29,
    sc_seats: 16,
    st_seats: 8,
    ews_seats: 11,
    pwd_general_seats: 2,
    pwd_obc_seats: 2,
    pwd_sc_seats: 1,
    pwd_st_seats: 1,
    pwd_ews_seats: 0,
  },
  2: {
    general_seats: 22,
    obc_seats: 15,
    sc_seats: 8,
    st_seats: 4,
    ews_seats: 6,
    pwd_general_seats: 1,
    pwd_obc_seats: 1,
    pwd_sc_seats: 1,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  3: {
    general_seats: 22,
    obc_seats: 15,
    sc_seats: 9,
    st_seats: 4,
    ews_seats: 6,
    pwd_general_seats: 1,
    pwd_obc_seats: 1,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  4: {
    general_seats: 45,
    obc_seats: 29,
    sc_seats: 16,
    st_seats: 8,
    ews_seats: 11,
    pwd_general_seats: 2,
    pwd_obc_seats: 2,
    pwd_sc_seats: 1,
    pwd_st_seats: 1,
    pwd_ews_seats: 1,
  },
  5: {
    general_seats: 44,
    obc_seats: 30,
    sc_seats: 16,
    st_seats: 8,
    ews_seats: 11,
    pwd_general_seats: 2,
    pwd_obc_seats: 1,
    pwd_sc_seats: 1,
    pwd_st_seats: 1,
    pwd_ews_seats: 1,
  },
  6: {
    general_seats: 25,
    obc_seats: 16,
    sc_seats: 9,
    st_seats: 5,
    ews_seats: 6,
    pwd_general_seats: 1,
    pwd_obc_seats: 1,
    pwd_sc_seats: 1,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  7: {
    general_seats: 12,
    obc_seats: 8,
    sc_seats: 5,
    st_seats: 2,
    ews_seats: 3,
    pwd_general_seats: 1,
    pwd_obc_seats: 1,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  },
  8: {
    general_seats: 44,
    obc_seats: 30,
    sc_seats: 16,
    st_seats: 8,
    ews_seats: 11,
    pwd_general_seats: 2,
    pwd_obc_seats: 1,
    pwd_sc_seats: 1,
    pwd_st_seats: 1,
    pwd_ews_seats: 1,
  },
  9: {
    general_seats: 43,
    obc_seats: 27,
    sc_seats: 15,
    st_seats: 8,
    ews_seats: 11,
    pwd_general_seats: 2,
    pwd_obc_seats: 1,
    pwd_sc_seats: 1,
    pwd_st_seats: 1,
    pwd_ews_seats: 1,
  },
  10: {
    general_seats: 12,
    obc_seats: 8,
    sc_seats: 4,
    st_seats: 3,
    ews_seats: 2,
    pwd_general_seats: 1,
    pwd_obc_seats: 0,
    pwd_sc_seats: 0,
    pwd_st_seats: 0,
    pwd_ews_seats: 0,
  }
};

module.exports = collegeSeatsWithId;