const studentMeritList = [
  {
    regNo: "1",
    generalRank: 1,
    category: "obc",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "2",
    generalRank: 3,
    category: "obc",
    categoryRank: 2,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "3",
    generalRank: 4,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "4",
    generalRank: 6,
    category: "sc",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "5",
    generalRank: 7,
    category: "sc",
    categoryRank: 2,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "6",
    generalRank: 8,
    category: "obc",
    categoryRank: 3,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "7",
    generalRank: 9,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "8",
    generalRank: 10,
    category: "st",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "9",
    generalRank: 11,
    category: "st",
    categoryRank: 2,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "10",
    generalRank: 12,
    category: "ews",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "11",
    generalRank: 13,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "12",
    generalRank: 14,
    category: "pwd_general",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "700",
    generalRank: 810,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "701",
    generalRank: 811,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "702",
    generalRank: 812,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "703",
    generalRank: 813,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "704",
    generalRank: 814,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "705",
    generalRank: 815,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "706",
    generalRank: 816,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "707",
    generalRank: 817,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "708",
    generalRank: 818,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "709",
    generalRank: 819,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "710",
    generalRank: 820,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "711",
    generalRank: 821,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "712",
    generalRank: 822,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "713",
    generalRank: 823,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "714",
    generalRank: 824,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "715",
    generalRank: 825,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "716",
    generalRank: 826,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "717",
    generalRank: 827,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "718",
    generalRank: 828,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "719",
    generalRank: 829,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "720",
    generalRank: 830,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "721",
    generalRank: 831,
    category: "obc",
    categoryRank: 151,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "722",
    generalRank: 832,
    category: "obc",
    categoryRank: 152,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "723",
    generalRank: 833,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "724",
    generalRank: 834,
    category: "sc",
    categoryRank: 76,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "725",
    generalRank: 835,
    category: "sc",
    categoryRank: 77,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "726",
    generalRank: 836,
    category: "obc",
    categoryRank: 153,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "727",
    generalRank: 837,
    category: "obc",
    categoryRank: 154,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "728",
    generalRank: 838,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "729",
    generalRank: 839,
    category: "st",
    categoryRank: 32,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "730",
    generalRank: 840,
    category: "obc",
    categoryRank: 155,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "731",
    generalRank: 841,
    category: "sc",
    categoryRank: 78,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "732",
    generalRank: 842,
    category: "sc",
    categoryRank: 79,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "733",
    generalRank: 843,
    category: "obc",
    categoryRank: 156,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "734",
    generalRank: 844,
    category: "obc",
    categoryRank: 157,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "735",
    generalRank: 845,
    category: "obc",
    categoryRank: 158,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "736",
    generalRank: 846,
    category: "pwd_general",
    categoryRank: 36,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "737",
    generalRank: 847,
    category: "st",
    categoryRank: 33,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "738",
    generalRank: 848,
    category: "pwd_sc",
    categoryRank: 30,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "739",
    generalRank: 849,
    category: "st",
    categoryRank: 37,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "740",
    generalRank: 850,
    category: "obc",
    categoryRank: 159,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "741",
    generalRank: 851,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "742",
    generalRank: 852,
    category: "obc",
    categoryRank: 160,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "743",
    generalRank: 853,
    category: "sc",
    categoryRank: 80,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "744",
    generalRank: 854,
    category: "sc",
    categoryRank: 81,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "745",
    generalRank: 855,
    category: "st",
    categoryRank: 34,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "746",
    generalRank: 856,
    category: "obc",
    categoryRank: 161,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "747",
    generalRank: 857,
    category: "pwd_obc",
    categoryRank: 31,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "748",
    generalRank: 858,
    category: "obc",
    categoryRank: 162,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "749",
    generalRank: 859,
    category: "pwd_obc",
    categoryRank: 32,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },

  {
    regNo: "750",
    generalRank: 860,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "751",
    generalRank: 861,
    category: "obc",
    categoryRank: 162,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "752",
    generalRank: 862,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "753",
    generalRank: 863,
    category: "obc",
    categoryRank: 163,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "754",
    generalRank: 864,
    category: "st",
    categoryRank: 35,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "755",
    generalRank: 865,
    category: "pwd_obc",
    categoryRank: 33,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "756",
    generalRank: 866,
    category: "pwd_sc",
    categoryRank: 30,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "757",
    generalRank: 867,
    category: "pwd_st",
    categoryRank: 15,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "758",
    generalRank: 868,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "759",
    generalRank: 869,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "760",
    generalRank: 870,
    category: "obc",
    categoryRank: 164,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "761",
    generalRank: 871,
    category: "pwd_sc",
    categoryRank: 31,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "762",
    generalRank: 872,
    category: "obc",
    categoryRank: 165,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "763",
    generalRank: 873,
    category: "sc",
    categoryRank: 82,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "764",
    generalRank: 874,
    category: "sc",
    categoryRank: 83,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "765",
    generalRank: 875,
    category: "obc",
    categoryRank: 166,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "766",
    generalRank: 876,
    category: "st",
    categoryRank: 36,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "767",
    generalRank: 877,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "768",
    generalRank: 878,
    category: "pwd_general",
    categoryRank: 38,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "769",
    generalRank: 879,
    category: "pwd_obc",
    categoryRank: 34,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "770",
    generalRank: 880,
    category: "pwd_ews",
    categoryRank: 36,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "771",
    generalRank: 881,
    category: "obc",
    categoryRank: 167,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "772",
    generalRank: 882,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "773",
    generalRank: 883,
    category: "obc",
    categoryRank: 168,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "774",
    generalRank: 884,
    category: "obc",
    categoryRank: 169,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "775",
    generalRank: 885,
    category: "pwd_ews",
    categoryRank: 37,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "776",
    generalRank: 886,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "777",
    generalRank: 887,
    category: "pwd_general",
    categoryRank: 39,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "778",
    generalRank: 888,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "779",
    generalRank: 889,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "780",
    generalRank: 890,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "781",
    generalRank: 891,
    category: "pwd_ews",
    categoryRank: 38,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "782",
    generalRank: 892,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "783",
    generalRank: 893,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "784",
    generalRank: 894,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "785",
    generalRank: 895,
    category: "pwd_sc",
    categoryRank: 32,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "786",
    generalRank: 896,
    preferences: ["1", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "787",
    generalRank: 897,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "788",
    generalRank: 898,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "789",
    generalRank: 899,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "790",
    generalRank: 900,
    category: "pwd_ews",
    categoryRank: 39,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "791",
    generalRank: 901,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "792",
    generalRank: 902,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "793",
    generalRank: 903,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "794",
    generalRank: 904,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "795",
    generalRank: 905,
    category: "pwd_st",
    categoryRank: 16,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "796",
    generalRank: 906,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "797",
    generalRank: 907,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "798",
    generalRank: 908,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "799",
    generalRank: 909,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
];

module.exports = studentMeritList;
