const studentMeritList = [
  {
    regNo: "400",
    generalRank: 516,
    category: "obc",
    categoryRank: 72,
    preferences: ["7", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "401",
    generalRank: 518,
    category: "obc",
    categoryRank: 73,
    preferences: ["8", "9", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "402",
    generalRank: 520,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "403",
    generalRank: 521,
    category: "sc",
    categoryRank: 36,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "404",
    generalRank: 522,
    category: "sc",
    categoryRank: 37,
    preferences: ["9", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "405",
    generalRank: 524,
    category: "obc",
    categoryRank: 74,
    preferences: ["5", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "406",
    generalRank: 525,
    preferences: ["8", "7", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "407",
    generalRank: 527,
    category: "st",
    categoryRank: 17,
    preferences: ["1", "2", "3", "4", "6", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "408",
    generalRank: 528,
    category: "st",
    categoryRank: 18,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "409",
    generalRank: 529,
    category: "ews",
    categoryRank: 21,
    preferences: ["1"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "410",
    generalRank: 530,
    preferences: ["2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "411",
    generalRank: 531,
    category: "pwd_general",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "412",
    generalRank: 532,
    category: "obc",
    categoryRank: 75,
    preferences: ["1", "2", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "413",
    generalRank: 533,
    category: "sc",
    categoryRank: 38,
    preferences: ["9", "1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "414",
    generalRank: 535,
    preferences: ["1", "2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "415",
    generalRank: 536,
    preferences: ["1", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "416",
    generalRank: 537,
    category: "sc",
    categoryRank: 39,
    preferences: ["1", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "417",
    generalRank: 538,
    category: "obc",
    categoryRank: 76,
    preferences: ["1", "2", "3", "4", "6", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "418",
    generalRank: 540,
    category: "pwd_ews",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "419",
    generalRank: 541,
    preferences: ["6", "5", "7", "8", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "420",
    generalRank: 542,
    preferences: ["6", "1", "2", "3", "4", "9", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "421",
    generalRank: 543,
    category: "ews",
    categoryRank: 22,
    preferences: ["5", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "422",
    generalRank: 544,
    preferences: ["5", "6", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "423",
    generalRank: 545,
    category: "pwd_obc",
    categoryRank: 16,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "424",
    generalRank: 546,
    category: "obc",
    categoryRank: 77,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "425",
    generalRank: 547,
    category: "obc",
    categoryRank: 78,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "426",
    generalRank: 548,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "427",
    generalRank: 549,
    category: "sc",
    categoryRank: 40,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "428",
    generalRank: 551,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "429",
    generalRank: 552,
    category: "obc",
    categoryRank: 79,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "430",
    generalRank: 553,
    preferences: ["2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "431",
    generalRank: 554,
    category: "pwd_st",
    categoryRank: 8,
    preferences: ["3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "432",
    generalRank: 555,
    preferences: ["3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "433",
    generalRank: 556,
    preferences: ["1", "2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "434",
    generalRank: 557,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "435",
    generalRank: 558,
    category: "pwd_general",
    categoryRank: 22,
    preferences: ["1", "2", "7", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "436",
    generalRank: 559,
    category: "obc",
    categoryRank:80,
    preferences: ["1", "2", "8", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "437",
    generalRank: 558,
    category: "obc",
    categoryRank: 81,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "438",
    generalRank: 559,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "439",
    generalRank: 560,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "440",
    generalRank: 561,
    preferences: ["5", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "441",
    generalRank: 562,
    category: "obc",
    categoryRank: 82,
    preferences: ["6", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "442",
    generalRank: 563,
    preferences: ["7", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "443",
    generalRank: 564,
    preferences: ["8", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "444",
    generalRank: 565,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "445",
    generalRank: 566,
    category: "ews",
    categoryRank: 23,
    preferences: ["5", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "446",
    generalRank: 567,
    preferences: ["6", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "447",
    generalRank: 569,
    category: "pwd_general",
    categoryRank: 23,
    preferences: ["7", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "448",
    generalRank: 570,
    category: "obc",
    categoryRank: 83,
    preferences: ["8", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "449",
    generalRank: 572,
    category: "obc",
    categoryRank: 84,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "450",
    generalRank: 573,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "451",
    generalRank: 574,
    preferences: ["1", "5", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "452",
    generalRank: 575,
    preferences: ["1", "6", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "453",
    generalRank: 576,
    category: "obc",
    categoryRank: 85,
    preferences: ["1", "7", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "454",
    generalRank: 577,
    preferences: ["1", "8", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "455",
    generalRank: 578,
    preferences: ["1", "9", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "456",
    generalRank: 579,
    preferences: ["1", "2", "5", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "457",
    generalRank: 580,
    preferences: ["1", "2", "6", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "458",
    generalRank: 5811,
    preferences: ["1", "2", "7", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "459",
    generalRank: 582,
    category: "pwd_general",
    categoryRank: 24,
    preferences: ["1", "2", "8", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "460",
    generalRank: 583,
    category: "obc",
    categoryRank: 86,
    preferences: ["1", "2", "9", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "461",
    generalRank: 584,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "462",
    generalRank: 585,
    preferences: ["1", "2", "3", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "463",
    generalRank: 586,
    preferences: ["1", "2", "3", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "464",
    generalRank: 587,
    preferences: ["1", "2", "3", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "465",
    generalRank: 588,
    category: "pwd_obc",
    categoryRank: 17,
    preferences: ["1", "2", "3", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "466",
    generalRank: 589,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "467",
    generalRank: 590,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "468",
    generalRank: 591,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "469",
    generalRank: 592,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "470",
    generalRank: 493,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "471",
    generalRank: 594,
    preferences: ["1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "472",
    generalRank: 595,
    preferences: ["1", "2", "3", "4", "5", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "473",
    generalRank: 596,
    preferences: ["1", "2", "3", "4", "5", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "474",
    generalRank: 597,
    preferences: ["1", "2", "3", "4", "5", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "475",
    generalRank: 598,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "476",
    generalRank: 599,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "477",
    generalRank: 600,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "478",
    generalRank: 601,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "479",
    generalRank: 602,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "480",
    generalRank: 603,
    category: "pwd_st",
    categoryRank: 7,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "481",
    generalRank: 604,
    preferences: ["1", "2", "3", "4", "6", "8", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "482",
    generalRank: 605,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "483",
    generalRank: 606,
    preferences: ["1", "2", "3", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "484",
    generalRank: 607,
    category: "pwd_obc",
    categoryRank: 18,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "485",
    generalRank: 608,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "486",
    generalRank: 609,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "487",
    generalRank: 610,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "488",
    generalRank: 611,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "489",
    generalRank: 612,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "490",
    generalRank: 613,
    preferences: ["1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "491",
    generalRank: 614,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "492",
    generalRank: 615,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "493",
    generalRank: 616,
    category: "ews",
    categoryRank: 24,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "494",
    generalRank: 617,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "495",
    generalRank: 618,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "496",
    generalRank: 619,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "497",
    generalRank: 620,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "498",
    generalRank: 621,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },{
    regNo: "499",
    generalRank: 622,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "400",
    generalRank: 516,
    category: "obc",
    categoryRank: 72,
    preferences: ["7", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "401",
    generalRank: 518,
    category: "obc",
    categoryRank: 73,
    preferences: ["8", "9", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "402",
    generalRank: 520,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "403",
    generalRank: 521,
    category: "sc",
    categoryRank: 36,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "404",
    generalRank: 522,
    category: "sc",
    categoryRank: 37,
    preferences: ["9", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "405",
    generalRank: 524,
    category: "obc",
    categoryRank: 74,
    preferences: ["5", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "406",
    generalRank: 525,
    preferences: ["8", "7", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "407",
    generalRank: 527,
    category: "st",
    categoryRank: 17,
    preferences: ["1", "2", "3", "4", "6", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "408",
    generalRank: 528,
    category: "st",
    categoryRank: 18,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "409",
    generalRank: 529,
    category: "ews",
    categoryRank: 21,
    preferences: ["1"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "410",
    generalRank: 530,
    preferences: ["2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "411",
    generalRank: 531,
    category: "pwd_general",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "412",
    generalRank: 532,
    category: "obc",
    categoryRank: 75,
    preferences: ["1", "2", "3", "4", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "413",
    generalRank: 533,
    category: "sc",
    categoryRank: 38,
    preferences: ["9", "1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "414",
    generalRank: 535,
    preferences: ["1", "2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "415",
    generalRank: 536,
    preferences: ["1", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "416",
    generalRank: 537,
    category: "sc",
    categoryRank: 39,
    preferences: ["1", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "417",
    generalRank: 538,
    category: "obc",
    categoryRank: 76,
    preferences: ["1", "2", "3", "4", "6", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "418",
    generalRank: 540,
    category: "pwd_ews",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "419",
    generalRank: 541,
    preferences: ["6", "5", "7", "8", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "420",
    generalRank: 542,
    preferences: ["6", "1", "2", "3", "4", "9", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "421",
    generalRank: 543,
    category: "ews",
    categoryRank: 22,
    preferences: ["5", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "422",
    generalRank: 544,
    preferences: ["5", "6", "1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "423",
    generalRank: 545,
    category: "pwd_obc",
    categoryRank: 16,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "424",
    generalRank: 546,
    category: "obc",
    categoryRank: 77,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "425",
    generalRank: 547,
    category: "obc",
    categoryRank: 78,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "426",
    generalRank: 548,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "427",
    generalRank: 549,
    category: "sc",
    categoryRank: 40,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "428",
    generalRank: 551,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "429",
    generalRank: 552,
    category: "obc",
    categoryRank: 79,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "430",
    generalRank: 553,
    preferences: ["2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "431",
    generalRank: 554,
    category: "pwd_st",
    categoryRank: 8,
    preferences: ["3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "432",
    generalRank: 555,
    preferences: ["3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "433",
    generalRank: 556,
    preferences: ["1", "2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "434",
    generalRank: 557,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "435",
    generalRank: 558,
    category: "pwd_general",
    categoryRank: 22,
    preferences: ["1", "2", "7", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "436",
    generalRank: 559,
    category: "obc",
    categoryRank:80,
    preferences: ["1", "2", "8", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "437",
    generalRank: 558,
    category: "obc",
    categoryRank: 81,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "438",
    generalRank: 559,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "439",
    generalRank: 560,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "440",
    generalRank: 561,
    preferences: ["5", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "441",
    generalRank: 562,
    category: "obc",
    categoryRank: 82,
    preferences: ["6", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "442",
    generalRank: 563,
    preferences: ["7", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "443",
    generalRank: 564,
    preferences: ["8", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "444",
    generalRank: 565,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "445",
    generalRank: 566,
    category: "ews",
    categoryRank: 23,
    preferences: ["5", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "446",
    generalRank: 567,
    preferences: ["6", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "447",
    generalRank: 569,
    category: "pwd_general",
    categoryRank: 23,
    preferences: ["7", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "448",
    generalRank: 570,
    category: "obc",
    categoryRank: 83,
    preferences: ["8", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "449",
    generalRank: 572,
    category: "obc",
    categoryRank: 84,
    preferences: ["9", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "450",
    generalRank: 573,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "451",
    generalRank: 574,
    preferences: ["1", "5", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "452",
    generalRank: 575,
    preferences: ["1", "6", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "453",
    generalRank: 576,
    category: "obc",
    categoryRank: 85,
    preferences: ["1", "7", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "454",
    generalRank: 577,
    preferences: ["1", "8", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "455",
    generalRank: 578,
    preferences: ["1", "9", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "456",
    generalRank: 579,
    preferences: ["1", "2", "5", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "457",
    generalRank: 580,
    preferences: ["1", "2", "6", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "458",
    generalRank: 5811,
    preferences: ["1", "2", "7", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "459",
    generalRank: 582,
    category: "pwd_general",
    categoryRank: 24,
    preferences: ["1", "2", "8", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "460",
    generalRank: 583,
    category: "obc",
    categoryRank: 86,
    preferences: ["1", "2", "9", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "461",
    generalRank: 584,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "462",
    generalRank: 585,
    preferences: ["1", "2", "3", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "463",
    generalRank: 586,
    preferences: ["1", "2", "3", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "464",
    generalRank: 587,
    preferences: ["1", "2", "3", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "465",
    generalRank: 588,
    category: "pwd_obc",
    categoryRank: 17,
    preferences: ["1", "2", "3", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "466",
    generalRank: 589,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "467",
    generalRank: 590,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "468",
    generalRank: 591,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "469",
    generalRank: 592,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "470",
    generalRank: 493,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "471",
    generalRank: 594,
    preferences: ["1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "472",
    generalRank: 595,
    preferences: ["1", "2", "3", "4", "5", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "473",
    generalRank: 596,
    preferences: ["1", "2", "3", "4", "5", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "474",
    generalRank: 597,
    preferences: ["1", "2", "3", "4", "5", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "475",
    generalRank: 598,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "476",
    generalRank: 599,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "477",
    generalRank: 600,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "478",
    generalRank: 601,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "479",
    generalRank: 602,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "480",
    generalRank: 603,
    category: "pwd_st",
    categoryRank: 7,
    preferences: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "481",
    generalRank: 604,
    preferences: ["1", "2", "3", "4", "6", "8", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "482",
    generalRank: 605,
    preferences: ["1", "2", "3", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "483",
    generalRank: 606,
    preferences: ["1", "2", "3", "6", "7", "8", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "484",
    generalRank: 607,
    category: "pwd_obc",
    categoryRank: 18,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "485",
    generalRank: 608,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "486",
    generalRank: 609,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "487",
    generalRank: 610,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "488",
    generalRank: 611,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "489",
    generalRank: 612,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "490",
    generalRank: 613,
    preferences: ["1", "2", "3", "4", "5", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "491",
    generalRank: 614,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "492",
    generalRank: 615,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "493",
    generalRank: 616,
    category: "ews",
    categoryRank: 24,
    preferences: ["1", "2", "3", "4", "9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "494",
    generalRank: 617,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "495",
    generalRank: 618,
    preferences: ["1", "2", "3", "4", "6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "496",
    generalRank: 619,
    preferences: ["1", "2", "3", "4", "7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "497",
    generalRank: 620,
    preferences: ["1", "2", "3", "4", "8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "498",
    generalRank: 621,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },{
    regNo: "499",
    generalRank: 622,
    preferences: ["1", "2", "3", "4", "5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
];

module.exports = studentMeritList;