const studentMeritList = [
  {
    regNo: "1",
    generalRank: 1,
    category: "obc",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "2",
    generalRank: 3,
    category: "obc",
    categoryRank: 122,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "3",
    generalRank: 4,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "4",
    generalRank: 6,
    category: "sc",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "5",
    generalRank: 7,
    category: "sc",
    categoryRank: 2,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "6",
    generalRank: 8,
    category: "obc",
    categoryRank: 123,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "7",
    generalRank: 9,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "8",
    generalRank: 10,
    category: "st",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "9",
    generalRank: 11,
    category: "st",
    categoryRank: 2,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "10",
    generalRank: 12,
    category: "ews",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "11",
    generalRank: 13,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "12",
    generalRank: 14,
    category: "pwd_general",
    categoryRank: 1,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "500",
    generalRank: 630,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "501",
    generalRank: 631,
    category: "sc",
    categoryRank: 41,
    preferences: ["1", "2", "3", "4","5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "502",
    generalRank: 632,
    category: "sc",
    categoryRank: 42,
    preferences: ["1", "2", "3", "4","5","6","7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "503",
    generalRank: 633,
    category: "obc",
    categoryRank: 124,
    preferences: ["1", "2", "3", "4","5","6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "504",
    generalRank: 634,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "505",
    generalRank: 635,
    category: "st",
    categoryRank: 22,
    preferences: ["1", "2", "3"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "506",
    generalRank: 636,
    category: "st",
    categoryRank: 23,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "507",
    generalRank: 637,
    category: "ews",
    categoryRank: 26,
    preferences: ["1", "2", "3"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "508",
    generalRank: 638,
    preferences: ["1", "2"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "509",
    generalRank: 639,
    category: "pwd_general",
    categoryRank: 26,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "510",
    generalRank: 640,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "511",
    generalRank: 641,
    category: "sc",
    categoryRank: 43,
    preferences: ["1", "2", "3", "4","5","6","7","8","9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "512",
    generalRank: 642,
    category: "sc",
    categoryRank: 44,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "513",
    generalRank: 643,
    category: "obc",
    categoryRank: 125,
    preferences: ["1", "2", "3", "4","5","6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "514",
    generalRank: 644,
    preferences: ["1", "2", "3"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "515",
    generalRank: 645,
    category: "st",
    categoryRank: 24,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "516",
    generalRank: 646,
    category: "st",
    categoryRank: 25,
    preferences: ["1", "2", "3"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "517",
    generalRank: 647,
    category: "ews",
    categoryRank: 27,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "518",
    generalRank: 648,
    preferences: ["1", "2", "3", "4","5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "519",
    generalRank: 649,
    category: "pwd_general",
    categoryRank: 27,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "520",
    generalRank: 650,
    preferences: ["1", "2", "3", "4","5","6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "521",
    generalRank: 651,
    category: "sc",
    categoryRank: 45,
    preferences: ["1", "2", "3"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "522",
    generalRank: 652,
    category: "sc",
    categoryRank: 46,
    preferences: ["1", "2", "3", "4","5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "523",
    generalRank: 653,
    category: "obc",
    categoryRank: 126,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "524",
    generalRank: 654,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "525",
    generalRank: 655,
    preferences: ["1", "2", "3", "4","5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "526",
    generalRank: 656,
    preferences: ["1", "2", "3", "4","5"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "527",
    generalRank: 657,
    category: "ews",
    categoryRank: 28,
    preferences: ["1", "2", "3", "4","6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "528",
    generalRank: 658,
    preferences: ["1", "2", "3", "4","7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "529",
    generalRank: 659,
    category: "pwd_general",
    categoryRank: 28,
    preferences: ["1", "2", "3", "4","8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "530",
    generalRank: 660,
    preferences: ["1", "2", "3", "4","9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "531",
    generalRank: 661,
    preferences: ["1", "2", "3", "4","8"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "532",
    generalRank: 662,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "533",
    generalRank: 663,
    category: "obc",
    categoryRank: 127,
    preferences: ["1", "2", "3", "4","9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "534",
    generalRank: 664,
    preferences: ["1", "2", "3", "4","6"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "535",
    generalRank: 665,
    preferences: ["1", "2", "3", "4","9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "536",
    generalRank: 666,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "537",
    generalRank: 667,
    category: "ews",
    categoryRank: 29,
    preferences: ["1", "2", "3", "4","7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "538",
    generalRank: 668,
    preferences: ["1", "2", "3", "4","9"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "539",
    generalRank: 669,
    category: "pwd_general",
    categoryRank: 29,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "540",
    generalRank: 670,
    preferences: ["1", "2", "3", "4","7"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "550",
    generalRank: 1200,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "549",
    generalRank: 1201,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "548",
    generalRank: 1202,
    category: "obc",
    categoryRank: 128,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "547",
    generalRank: 1203,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "546",
    generalRank: 1204,
    category: "pwd_st",
    categoryRank: 9,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "545",
    generalRank: 1205,
    category: "pwd_st",
    categoryRank: 10,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "544",
    generalRank: 1206,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "543",
    generalRank: 1207,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "542",
    generalRank: 1208,
    category: "pwd_general",
    categoryRank: 30,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "541",
    generalRank: 1209,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "551",
    generalRank: 1210,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "552",
    generalRank: 1211,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "553",
    generalRank: 1212,
    category: "obc",
    categoryRank: 129,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "554",
    generalRank: 1213,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "555",
    generalRank: 1214,
    category: "pwd_st",
    categoryRank: 11,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "556",
    generalRank: 1215,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "557",
    generalRank: 1216,
    category: "pwd_ews",
    categoryRank: 26,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "558",
    generalRank: 1217,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "559",
    generalRank: 1218,
    category: "pwd_obc",
    categoryRank: 20,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "560",
    generalRank: 1219,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "561",
    generalRank: 1220,
    category: "pwd_sc",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "562",
    generalRank: 1221,
    category: "pwd_sc",
    categoryRank: 22,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "563",
    generalRank: 1222,
    category: "obc",
    categoryRank: 130,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "564",
    generalRank: 1223,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "565",
    generalRank: 1224,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "566",
    generalRank: 1225,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "567",
    generalRank: 1226,
    category: "pwd_ews",
    categoryRank: 27,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "568",
    generalRank: 1227,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "569",
    generalRank: 1228,
    category: "pwd_sc",
    categoryRank: 23,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "570",
    generalRank: 1229,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "571",
    generalRank: 1230,
    category: "pwd_sc",
    categoryRank: 24,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "572",
    generalRank: 1231,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "573",
    generalRank: 1232,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "574",
    generalRank: 1233,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "575",
    generalRank: 1234,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "576",
    generalRank: 1235,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "577",
    generalRank: 1236,
    category: "pwd_ews",
    categoryRank: 28,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "578",
    generalRank: 1237,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "579",
    generalRank: 1238,
    category: "pwd_ews",
    categoryRank: 29,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "580",
    generalRank: 1239,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "581",
    generalRank: 1240,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "582",
    generalRank: 1241,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "583",
    generalRank: 1242,
    category: "pwd_obc",
    categoryRank: 21,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "584",
    generalRank: 1243,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "585",
    generalRank: 1244,
    category: "pwd_obc",
    categoryRank: 22,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "586",
    generalRank: 1245,
    category: "pwd_obc",
    categoryRank: 23,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "587",
    generalRank: 1246,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "588",
    generalRank: 1247,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "589",
    generalRank: 1248,
    category: "pwd_obc",
    categoryRank: 24,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "590",
    generalRank: 1249,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "591",
    generalRank: 1250,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "592",
    generalRank: 1251,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "593",
    generalRank: 1252,
    category: "pwd_obc",
    categoryRank: 25,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "594",
    generalRank: 1253,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "595",
    generalRank: 1254,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "596",
    generalRank: 1255,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "597",
    generalRank: 1256,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "598",
    generalRank: 1257,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
  {
    regNo: "599",
    generalRank: 1258,
    preferences: ["1", "2", "3", "4"],
    currentSeatIndex: null,
    seatAllotmentCategory: null,
  },
];

module.exports = studentMeritList;
